jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - continue-on-error: true
      name: Build microservices with Maven
      run: cd microservice-kafka && ./mvnw -B package --file pom.xml
    - continue-on-error: true
      name: Create Docker images
      run: cd docker && docker-compose build
name: Build and Publish Docker Images
on:
  repository_dispatch:
    types: trigger-ga___build.yml
